In [2]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/adiacla/bigdata/refs/heads/master/pacientes.csv',sep=",")

In [3]:
df

     edad  colesterol  problema_cardiaco
0    63.0       233.0                  1
1     NaN       250.0                  0
2    37.0       250.0                  0
3    41.0       204.0                  0
4    56.0       236.0                  1
..    ...         ...                ...
297  63.0       187.0                  0
298  63.0       197.0                  0
299  59.0       176.0                  0
300  57.0       241.0                  1
301  45.0       264.0                  1

[302 rows x 3 columns]

In [4]:
df.shape

(302, 3)

In [5]:
df.dropna(inplace=True)

In [6]:
df.shape

(298, 3)

In [7]:
df.to_csv('cardiaco_limpio.csv', index=False)

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
edad,298.0,54.305369,9.084195,29.0,47.25,55.0,61.0,77.0
colesterol,298.0,246.926174,51.685998,126.0,211.25,241.5,275.0,564.0
problema_cardiaco,298.0,0.493289,0.500796,0.0,0.00,0.0,1.0,1.0

In [9]:
X = df[['edad','colesterol']]
y = df['problema_cardiaco']

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

In [11]:
X_test

     edad  colesterol
156  39.0       220.0
127  34.0       210.0
190  50.0       233.0
186  50.0       243.0
3    41.0       204.0
171  53.0       203.0
53   66.0       302.0
285  40.0       223.0
54   62.0       231.0
126  39.0       199.0
271  56.0       283.0
230  59.0       288.0
221  48.0       256.0
139  62.0       208.0
56   63.0       252.0
290  57.0       335.0
174  58.0       284.0
211  59.0       177.0
143  43.0       303.0
72   54.0       258.0
32   41.0       198.0
208  59.0       239.0
0    63.0       233.0
161  56.0       221.0
254  62.0       294.0
115  43.0       211.0
243  59.0       249.0
28   59.0       212.0
267  66.0       212.0
85   52.0       298.0
191  41.0       172.0
123  59.0       271.0
217  43.0       341.0
82   41.0       250.0
266  54.0       206.0
237  51.0       299.0
250  54.0       283.0
167  67.0       286.0
242  70.0       269.0
181  57.0       276.0
212  57.0       229.0
286  61.0       207.0
59   45.0       260.0
192  51.0       305.0
299  59.0       176.0
50   53.0       216.0
203  60.0       258.0
121  46.0       243.0
86   42.0       265.0
185  58.0       230.0
48   44.0       235.0
279  57.0       261.0
193  58.0       216.0
292  61.0       203.0
162  56.0       240.0
268  55.0       327.0
131  74.0       269.0
94   52.0       223.0
109  45.0       236.0
240  77.0       304.0

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [13]:
import joblib
joblib.dump(scaler, 'scaler.joblib')

['scaler.joblib']

In [14]:
X_train_scaled

array([[0.68085106, 0.26712329],
       [0.46808511, 0.23059361],
       [0.72340426, 0.16210046],
       [0.19148936, 0.11187215],
       [0.87234043, 0.44748858],
       [0.42553191, 0.33105023],
       [0.57446809, 0.64611872],
       [0.21276596, 0.21232877],
       [0.44680851, 0.26940639],
       [0.46808511, 0.19863014],
       [0.80851064, 0.23515982],
       [0.74468085, 0.31278539],
       [0.31914894, 0.21461187],
       [0.4893617 , 0.17808219],
       [0.70212766, 0.31278539],
       [0.38297872, 0.28995434],
       [0.31914894, 0.24429224],
       [0.38297872, 0.17808219],
       [0.72340426, 0.13926941],
       [0.59574468, 0.18493151],
       [0.44680851, 0.15981735],
       [0.70212766, 0.26940639],
       [0.89361702, 0.40182648],
       [0.55319149, 0.51826484],
       [0.70212766, 0.35388128],
       [0.61702128, 0.22374429],
       [0.27659574, 0.26027397],
       [0.63829787, 0.21004566],
       [0.72340426, 0.15753425],
       [0.46808511, 0.38584475],
       [0.65957447, 0.1347032 ],
       [0.4893617 , 0.16666667],
       [0.76595745, 0.2260274 ],
       [0.57446809, 0.29680365],
       [0.31914894, 0.37442922],
       [0.74468085, 0.42694064],
       [0.5106383 , 0.2739726 ],
       [0.34042553, 0.41552511],
       [0.29787234, 0.43150685],
       [0.40425532, 0.2716895 ],
       [0.72340426, 0.29223744],
       [0.53191489, 0.3652968 ],
       [0.78723404, 0.2283105 ],
       [0.78723404, 0.23287671],
       [0.36170213, 0.11643836],
       [0.46808511, 0.29680365],
       [0.17021277, 0.20319635],
       [0.82978723, 0.34474886],
       [0.12765957, 0.35616438],
       [0.53191489, 0.36986301],
       [0.5106383 , 0.24657534],
       [0.25531915, 0.24885845],
       [0.31914894, 0.16210046],
       [0.12765957, 0.15068493],
       [0.38297872, 0.29908676],
       [0.53191489, 0.17123288],
       [0.29787234, 0.11643836],
       [0.        , 0.17808219],
       [0.61702128, 0.2260274 ],
       [0.29787234, 0.27625571],
       [0.65957447, 0.28995434],
       [0.72340426, 0.64155251],
       [0.57446809, 0.38356164],
       [0.65957447, 0.38127854],
       [0.42553191, 0.3196347 ],
       [0.12765957, 0.16438356],
       [0.44680851, 0.21232877],
       [0.46808511, 0.41552511],
       [0.4893617 , 0.29452055],
       [0.63829787, 0.32876712],
       [0.59574468, 0.33789954],
       [0.36170213, 0.23972603],
       [0.55319149, 0.49315068],
       [0.5106383 , 0.35616438],
       [0.65957447, 0.35616438],
       [0.31914894, 0.09817352],
       [0.4893617 , 0.15981735],
       [0.4893617 , 0.17123288],
       [0.57446809, 0.36986301],
       [0.29787234, 0.27625571],
       [0.68085106, 0.0913242 ],
       [0.76595745, 0.35616438],
       [0.23404255, 0.16666667],
       [0.80851064, 0.22146119],
       [0.5106383 , 0.31506849],
       [0.19148936, 0.11187215],
       [0.46808511, 0.11187215],
       [0.57446809, 0.15296804],
       [0.10638298, 0.12785388],
       [0.80851064, 0.25342466],
       [0.74468085, 0.40410959],
       [0.74468085, 0.19634703],
       [0.53191489, 0.24200913],
       [0.4893617 , 0.1369863 ],
       [0.80851064, 1.        ],
       [0.36170213, 0.16210046],
       [0.34042553, 0.31506849],
       [0.82978723, 0.33789954],
       [0.36170213, 0.17808219],
       [0.70212766, 0.61187215],
       [0.72340426, 0.46575342],
       [0.61702128, 0.21004566],
       [0.53191489, 0.41780822],
       [0.40425532, 0.34018265],
       [0.17021277, 0.28310502],
       [0.76595745, 0.29223744],
       [0.87234043, 0.10958904],
       [0.42553191, 0.14155251],
       [0.23404255, 0.09360731],
       [0.82978723, 0.19406393],
       [0.76595745, 0.53424658],
       [0.59574468, 0.17123288],
       [0.4893617 , 0.23744292],
       [0.59574468, 0.24200913],
       [0.74468085, 0.41780822],
       [0.42553191, 0.05251142],
       [0.63829787, 0.24657534],
       [0.53191489, 0.25799087],
       [0.85106383, 0.24657534],
       [0.36170213, 0.42237443],
       [0.5106383 , 0.16210046],
       [0.59574468, 0.26255708],
       [0.61702128, 0.16210046],
       [0.53191489, 0.40639269],
       [0.34042553, 0.18721461],
       [0.78723404, 0.2739726 ],
       [0.34042553, 0.07762557],
       [0.27659574, 0.43150685],
       [0.55319149, 0.28310502],
       [0.72340426, 0.32648402],
       [0.61702128, 0.44063927],
       [0.59574468, 0.52054795],
       [0.76595745, 0.66438356],
       [0.53191489, 0.14155251],
       [0.78723404, 0.34703196],
       [0.59574468, 0.40410959],
       [0.21276596, 0.44520548],
       [0.31914894, 0.03424658],
       [0.4893617 , 0.19634703],
       [0.4893617 , 0.24429224],
       [0.74468085, 0.4543379 ],
       [0.85106383, 0.25799087],
       [0.87234043, 0.2716895 ],
       [0.40425532, 0.21917808],
       [0.68085106, 0.24657534],
       [0.59574468, 0.        ],
       [0.27659574, 0.12328767],
       [0.4893617 , 0.4543379 ],
       [0.27659574, 0.26940639],
       [0.46808511, 0.2716895 ],
       [0.55319149, 0.37214612],
       [0.80851064, 0.34474886],
       [0.63829787, 0.17808219],
       [0.57446809, 0.28082192],
       [0.55319149, 0.1803653 ],
       [0.59574468, 0.15068493],
       [0.65957447, 0.26027397],
       [0.25531915, 0.4109589 ],
       [0.38297872, 0.34018265],
       [0.68085106, 0.46575342],
       [0.31914894, 0.21232877],
       [0.65957447, 0.43835616],
       [0.29787234, 0.19863014],
       [0.76595745, 0.11643836],
       [0.25531915, 0.20091324],
       [0.76595745, 0.27853881],
       [0.59574468, 0.09589041],
       [0.61702128, 0.26027397],
       [0.61702128, 0.19406393],
       [0.59574468, 0.37214612],
       [0.61702128, 0.30365297],
       [0.80851064, 0.19634703],
       [0.89361702, 0.3173516 ],
       [0.70212766, 0.08675799],
       [0.42553191, 0.32648402],
       [0.34042553, 0.41780822],
       [0.44680851, 0.29223744],
       [0.55319149, 0.31050228],
       [0.63829787, 0.33561644],
       [0.63829787, 0.456621  ],
       [0.89361702, 0.05251142],
       [0.36170213, 0.28082192],
       [1.        , 0.16210046],
       [0.61702128, 0.43835616],
       [0.53191489, 0.3196347 ],
       [0.34042553, 0.24657534],
       [0.57446809, 0.13242009],
       [0.27659574, 0.2283105 ],
       [0.57446809, 0.25114155],
       [0.4893617 , 0.1803653 ],
       [0.74468085, 0.2739726 ],
       [0.25531915, 0.07077626],
       [0.70212766, 0.32191781],
       [0.78723404, 0.23287671],
       [0.40425532, 0.23515982],
       [0.80851064, 0.29223744],
       [0.46808511, 0.30821918],
       [0.31914894, 0.2283105 ],
       [0.27659574, 0.38584475],
       [0.61702128, 0.32876712],
       [0.65957447, 0.30136986],
       [0.31914894, 0.26484018],
       [0.61702128, 0.24657534],
       [0.46808511, 0.21917808],
       [0.46808511, 0.39269406],
       [0.70212766, 0.32420091],
       [0.38297872, 0.26712329],
       [0.65957447, 0.11872146],
       [0.61702128, 0.21461187],
       [0.27659574, 0.18949772],
       [0.61702128, 0.35844749],
       [0.25531915, 0.17579909],
       [0.53191489, 0.32191781],
       [0.65957447, 0.23744292],
       [0.40425532, 0.33789954],
       [0.63829787, 0.21689498],
       [0.55319149, 0.20776256],
       [0.74468085, 0.47716895],
       [0.76595745, 0.32648402],
       [0.61702128, 0.48858447],
       [0.61702128, 0.39726027],
       [0.5106383 , 0.2283105 ],
       [0.74468085, 0.23059361],
       [0.65957447, 0.1826484 ],
       [0.40425532, 0.29452055],
       [0.53191489, 0.25799087],
       [0.68085106, 0.41324201],
       [0.25531915, 0.32420091],
       [0.19148936, 0.23972603],
       [0.12765957, 0.13013699],
       [0.61702128, 0.27853881],
       [0.44680851, 0.16894977],
       [0.53191489, 0.20091324],
       [0.70212766, 0.18949772],
       [0.80851064, 0.39497717],
       [0.68085106, 0.30593607],
       [0.53191489, 0.33561644],
       [0.85106383, 0.29223744]])